[FEATURE]: Authors frontend page generation
Betarena/scores pull request #1942
Opened 2024-01-31 22:18 UTC by ihardz

![Static Badge](https://img.shields.io/badge/pull--request-%E2%9E%A8_branch%3Adev-black?logo=github&color=%230096FF%09&cacheSeconds=0)

### 📃 Description

- @ihardz authors page generation.

----

### 🎟️ Issues

- #1879

----

### 📌 Type of change

> Please remove checbox options (below) that are not relevant to `this` Pull-Request.

- [ ] 📑 Chore update
> (^) Changes that invlove simple **chore** / **maintenance** changes, such as: documentation, folder/file simple restructure, syntax, typos, code clean, etc.

- [ ] 🐞 Bug fix
> (^) Changes involving **small** and **minor** **bug-fixes**, such as: fixing functionality, fixing faulty logic, fixing errors, fixing error handling/exceptions, etc.

- [x] ⚡️ New feature
> (^) Changes involving **minor** and **major** new **feature/enhancements**, such as: new widget, new improvements, new endpoints, new pages, new logic

- [ ] ❌ Breaking change
> (^) **Major** changes that will and/or can cause **issues and functionality to break**, such as: major project restructiring, major project feature change, major project bug fix, major project endpoints update, etc.

----

### 🧰 How Has This Been Tested?

> Please describe the tests that you ran to verify your changes,
> by simply checking the appropiate checkbox 

- [x] `localhost`
- [ ] `heroku (DEV)`

----

### ✔ Self-checklist

> Please select the checkboxes that apply below, as a developer **self-checklist**.

- [ ] This code follows the style guidelines of this project.
- [ ] This code is self-reviewed.
- [ ] This code is peer-reviewed.
- [ ] This code is properly commented, __particularly in hard-to-understand areas__.
- [ ] Documentation has been updated.
- [ ] This code does not generate new warnings.
- [ ] This code contains added tests that prove my fix is effective or that my feature works.
- [ ] This code new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

----

### ⚠ Warning(s)

- `console.(..)`

> (^) Please ensure that your code does not contain `console` without the `if (dev) console...`
> to avoid memory overflows on the server. Use the internal `debug.ts` project methods to gurantee no `poroduction`
> leaks of `console` errors. Or remove the `console` if no longer needed.

----

2024-02-04 19:43 UTC, jonsnowpt requested changes
@ihardz Deepsource issues that need review.

2024-02-05 00:25 UTC, migbash commented on src/routes/(content)/a/[...permalink]/+page.svelte
_this_ should be moved to another component called `Layout.svelte` iniside the `/src/components` directory.
Check the existing `src/(scores)/**/+page.svelte` example(s).

2024-02-05 02:30 UTC, migbash requested changes
#### [1] Make use of `?? (nullish)` instead of `|| (logical OR)` for fallback values.

#### [2] Update `<script> [..] </script>` to use a similar structure, that provided in the `.docs/.templates/*` files.

#### [3] Use `Allman` code structure for everything. 

Check the existing `src/components/**` files for example.

#### [+] check comments/requests added to files in _this_ `Pull-Request` for resolution.

2024-02-05 02:30 UTC, migbash commented on src/lib/components/content-section/AuthorArticleHeading.svelte
Unecessary component. Too simple and can be just pushed to the `parent` that is importing it (making use of).

2024-02-05 02:30 UTC, migbash commented on src/lib/context/dark-theme-context.ts
Is there a need for this ?
We have exsiting methods that cover pretty much all aspects of JS dark mode handling from the `$userBetarenaSettings` store.

2024-02-05 02:30 UTC, migbash commented on src/lib/components/shared/gradients/SideGradientWrap.svelte
> +    hideOn.includes(deviceType) ? "unset" : "\"\"";
Typically, recommended to use the following for `listening` to device width:

```svelte
<svelte:window
  on:resize=
  {
    () => { return resizeCustom() }
  }
/>
```

Look for examples of this in the `components/` directory.

2024-02-05 09:55 UTC, migbash commented on src/lib/components/content-section/AuthorArticleContent.svelte
> +    }
I think you've miss understood, all I mean, is to remove the brackets `(..)` from `:global()`, nothing else. 

It should look like this:

```svelte
<style lang="scss">
  .author-article-content-component 
  {
    :global
    {
      a
      {
        /* 🎨 style */
        text-decoration: underline !important;
        display: inline;
      }

      h2,
      h3,
      h4,
      h5,
      h6
      {
        /* 🎨 style */
        font-weight: 800;
      }
    }
  }
</style>
```

2024-02-05 10:08 UTC, migbash commented on src/lib/components/_main_/header/header-content/sub-components/BrandLogo.svelte
> +  export let dark: boolean = false;
I don't think I understand your reasoining.

I am talking about the line :|: `export let dark: boolean = false;`.

We don't use `prop-drilling` in the project, such as you have done with the `{dark}` variable, which you pass from `+layout.svelte > HeaderContent.svelte > BrandLogo.svelte`, among other files in your pull-request.

Recommended to a `child` component to access such data via `context` and or `stores`, hence I suggested to use:

- getDarkThemeContext() or,
- $userBetarenaSettings.theme

, to obtain the `theme` state.

2024-02-05 10:12 UTC, migbash commented on src/lib/components/content-section/AuthorArticleDetails/AuthorArticleDetails.svelte
> +  let ai = true;
I think you have misunderstood, I am talking about `EsLint > (rule) one-var`, defined in the project `.eslintrc.yaml`:

https://eslint.org/docs/latest/rules/one-var#consecutive

Please enable the `EsLint`, as it appears it is not being refelected in your `Pull-Request`, which should give an error.

2024-02-05 10:18 UTC, migbash commented on src/lib/components/content-section/AuthorArticleDetails/AuthorArticleDetails.svelte
> +      display: none;
Change request stands. 

We do not use `display: none` in the project, and hide via `{if condition} {/if}`. 

Move from `CSS` breakpoints to `JS` breakpoints needs to be done.

1. `Blicking` does not happen, due to the existing `splashscreen` and with the `user-agent` decoding in the (server) 
`+layout.server.ts` that determines correct user device being used.

2024-02-05 10:26 UTC, migbash commented on src/lib/components/content-section/AuthorArticleDetails/DetailsTemplateMobile.svelte
> +  }
Change stands, global styles need to be used defined for the `project`.

Please see `static/app.css` to see what is available , or use the `CTRL+SPACE` (MacOS) when typing inside a `class=""` to see available classes.

It's fully configured to follow the `Figma Guidelines` and it's used throughout the project, with no changes done that can cause a `break`.

Only custom `Styles/CSS` are to be placed inside the `<style> </style>` for a `.svelte` component.

2024-02-05 10:29 UTC, migbash commented on src/lib/components/content-section/AuthorArticleDetails/AuthorArticleDetails.svelte
> +  </div>
Change request stands.

Should be merged into `1 single` component, handled with `JS` conditionals and/or `CSS` to mutate a single component to adjust for repective `device` being used, in this case.

2024-02-05 10:35 UTC, migbash commented on src/lib/components/content-section/AuthorArticleDetails/DetailsTemplateMobile.svelte
> +  export let ai: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477946889

2024-02-05 10:37 UTC, migbash commented on src/lib/components/_main_/auth/SignIn.svelte
> +  const handleButtonClick = sessionStore.toggleAuthShow;
Perfectly readbale!

Change request stands for such cases where `JS` **one-off** logic/functions exist in a component.

2024-02-05 10:42 UTC, migbash commented on src/lib/components/content-section/AuthorArticleContent.svelte
> +    }
> have you tried this and it works?

Please try my last [comment](https://github.com/Betarena/scores/pull/1942#discussion_r1477925191) in your `local` environment, (most) components use this `structure` for `global { .. }` handle.

2024-02-05 10:44 UTC, migbash commented on src/lib/components/_main_/header/header-content/HeaderContent.svelte
> +  export let dark: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477941491

2024-02-05 10:45 UTC, migbash commented on src/lib/components/_main_/header/header-content-mobile/HeaderContentMobile.svelte
> +  export let dark: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477941491

2024-02-05 10:46 UTC, migbash commented on src/lib/components/_main_/header/header-content-mobile/HeaderContentMobile.svelte
> +  <div class="wrap">
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477966597

2024-02-05 10:47 UTC, migbash commented on src/lib/components/content-section/AuthorArticleDetails/DetailsTemplateTablet.svelte
> +  export let ai: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477946889

2024-02-05 10:48 UTC, migbash commented on src/lib/components/content-section/AuthorBadges.svelte
> +  export let dark: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477941491

2024-02-05 10:48 UTC, migbash commented on src/lib/components/content-section/loaders/AuthorArticleContentLoader.svelte
> +  export let dark: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477941491

2024-02-05 10:48 UTC, migbash commented on src/lib/components/content-section/loaders/AuthorArticleDetailsLoader.svelte
> +  export let dark: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477941491

2024-02-05 10:48 UTC, migbash commented on src/lib/components/content-section/loaders/AuthorArticleImageLoader.svelte
> +  export let dark: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477941491

2024-02-05 10:48 UTC, migbash commented on src/lib/components/content-section/loaders/AuthorBadgesLoader.svelte
> +  export let dark: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477941491

2024-02-05 10:49 UTC, migbash commented on src/lib/components/shared/avatar/ProfileAvatar.svelte
> +  export let effect: boolean = false;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477946889

2024-02-05 10:50 UTC, migbash commented on src/lib/components/shared/buttons/ButtonHollow.svelte
> +  export let dark: boolean = true;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477946889

2024-02-05 10:50 UTC, migbash commented on src/lib/components/shared/buttons/ButtonSvgCircle.svelte
> +  export let opacity: number | undefined = 1;
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477946889

2024-02-05 10:50 UTC, migbash commented on src/lib/components/shared/gradients/SideGradientWrap.svelte
> +  export let hideOn: DeviceType[] = [];
see :|: https://github.com/Betarena/scores/pull/1942#discussion_r1477946889

2024-03-08 20:55 UTC, closed without merging