Dev
Betarena/scores pull request #2203
Opened 2024-06-19 18:07 UTC by Izobov

A lot of icons, thats why it contains 537 files changes 

Please `click on` the `(^) Preview` tab and select the appropriate sub-template:

- [Pull-Request Template into branch:dev](?expand=1&template=pr_to_dev.md)
- [Pull-Request Template into branch:main](?expand=1&template=pr_to_main.md)

2024-06-19 23:12 UTC, jonsnowpt approved these changes

2024-06-19 23:13 UTC, migbash requested changes
@Izobov 

Unecessary folder commit for `/static/flags/_MACOSX/flags/..`.

2024-06-19 23:54 UTC, migbash commented on src/lib/components/_main_/footer/FooterBottom.svelte
> +  $: isDesktop = $sessionStore.viewportType === "desktop";
Unecessary line, project preference is to use:

```
$: ({ viewportType } = $sessionStore);
[..]
<footer 
  class:mobile 
  class:desktop={viewportType === 'desktop'}
  class="dark-mode" 
>
```

2024-06-20 00:27 UTC, migbash approved these changes

2024-06-20 01:17 UTC, merged